INSERT Players (Name, IsHuman)
VALUES ('Dealer', 0),
		('Human', 1),
		('Computer', 0);
GO



INSERT Cards (Name, Value, Position, PhotoPath, PlayerId)
VALUES ('2 of Clubs', 2, 1, 'assets/img/2_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('3 of Clubs', 3, 2, 'assets/img/3_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('4 of Clubs', 4, 3, 'assets/img/4_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('5 of Clubs', 5, 4, 'assets/img/5_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('6 of Clubs', 6, 5, 'assets/img/6_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('7 of Clubs', 7, 6, 'assets/img/7_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('8 of Clubs', 8, 7, 'assets/img/8_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('9 of Clubs', 9, 8, 'assets/img/9_of_clubs.png', (SELECT Id from Players where name = 'Dealer')),
	   ('10 of Clubs', 10, 9, 'assets/img/10_of_clubs2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Jack of Clubs', 11, 10, 'assets/img/jack_of_clubs2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Queen of Clubs', 12, 11, 'assets/img/queen_of_clubs2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('King of Clubs', 13, 12, 'assets/img/king_of_clubs2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Ace of Clubs', 14, 13, 'assets/img/ace_of_clubs2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('2 of Diamonds', 2, 14, 'assets/img/2_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('3 of Diamonds', 3, 15, 'assets/img/3_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('4 of Diamonds', 4, 16, 'assets/img/4_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('5 of Diamonds', 5, 17, 'assets/img/5_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('6 of Diamonds', 6, 18, 'assets/img/6_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('7 of Diamonds', 7, 19, 'assets/img/7_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('8 of Diamonds', 8, 20, 'assets/img/8_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('9 of Diamonds', 9, 21, 'assets/img/9_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('10 of Diamonds', 10, 22, 'assets/img/10_of_diamonds.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Jack of Diamonds', 11, 23, 'assets/img/jack_of_diamonds2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Queen of Diamonds', 12, 24, 'assets/img/queen_of_diamonds2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('King of Diamonds', 13, 25, 'assets/img/king_of_diamonds2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Ace of Diamonds', 14, 26, 'assets/img/ace_of_diamonds2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('2 of Hearts', 2, 27, 'assets/img/2_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('3 of Hearts', 3, 28, 'assets/img/3_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('4 of Hearts', 4, 29, 'assets/img/4_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('5 of Hearts', 5, 30, 'assets/img/5_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('6 of Hearts', 6, 31, 'assets/img/6_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('7 of Hearts', 7, 32, 'assets/img/7_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('8 of Hearts', 8, 33, 'assets/img/8_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('9 of Hearts', 9, 34, 'assets/img/9_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('10 of Hearts', 10, 35, 'assets/img/10_of_hearts.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Jack of Hearts', 11, 36, 'assets/img/jack_of_hearts2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Queen of Hearts', 12, 37, 'assets/img/queen_of_hearts2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('King of Hearts', 13, 38, 'assets/img/king_of_hearts2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Ace of Hearts', 14, 39, 'assets/img/ace_of_hearts2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('2 of Spades', 2, 40, 'assets/img/2_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('3 of Spades', 3, 41, 'assets/img/3_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('4 of Spades', 4, 42, 'assets/img/4_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('5 of Spades', 5, 43, 'assets/img/5_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('6 of Spades', 6, 44, 'assets/img/6_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('7 of Spades', 7, 45, 'assets/img/7_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('8 of Spades', 8, 46, 'assets/img/8_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('9 of Spades', 9, 47, 'assets/img/9_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('10 of Spades', 10, 48, 'assets/img/10_of_spades.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Jack of Spades', 11, 49, 'assets/img/jack_of_spades2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Queen of Spades', 12, 50, 'assets/img/queen_of_spades2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('King of Spades', 13, 51, 'assets/img/king_of_spades2.png', (SELECT Id from Players where name = 'Dealer')),
	   ('Ace of Spades', 14, 52, 'assets/img/ace_of_spades2.png', (SELECT Id from Players where name = 'Dealer'));